const { chromium } = require('C:/Projects/fridge-to-fork/brag-output/work/node_modules/playwright');
const fs=require('fs'),path=require('path');
const OUT=path.join(__dirname,'cap');fs.rmSync(OUT,{recursive:true,force:true});fs.mkdirSync(OUT);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
  const browser=await chromium.launch();
  const ctx=await browser.newContext({viewport:{width:430,height:932},deviceScaleFactor:2,isMobile:true,hasTouch:true});
  const page=await ctx.newPage();
  page.on('pageerror',e=>console.log('PAGEERR',e.message));
  const cdp=await ctx.newCDPSession(page);
  const frames=[];let n=0;
  cdp.on('Page.screencastFrame',async({data,metadata,sessionId})=>{
    const i=n++;fs.writeFileSync(path.join(OUT,`c${String(i).padStart(5,'0')}.jpg`),Buffer.from(data,'base64'));
    frames.push(metadata.timestamp);cdp.send('Page.screencastFrameAck',{sessionId}).catch(()=>{});
  });
  await page.goto('http://localhost:8765/');
  await page.evaluate(()=>document.fonts.ready);await sleep(1500);
  const marks={};const t0=Date.now();
  await cdp.send('Page.startScreencast',{format:'jpeg',quality:92,maxWidth:860,maxHeight:1864,everyNthFrame:1});
  const T0=Date.now()/1000;
  const mark=k=>{marks[k]=Date.now()/1000};
  await page.addStyleTag({content:`.tapfx{position:fixed;width:64px;height:64px;margin:-32px 0 0 -32px;border-radius:50%;background:rgba(252,128,25,.45);border:3px solid rgba(252,128,25,.9);pointer-events:none;z-index:99999;animation:tapfx .5s ease-out forwards}@keyframes tapfx{from{transform:scale(.4);opacity:1}to{transform:scale(1.5);opacity:0}}`});
  const tap=async(sel)=>{const el=page.locator(sel).first();await el.scrollIntoViewIfNeeded();const b=await el.boundingBox();
    await page.evaluate(([x,y])=>{const d=document.createElement('div');d.className='tapfx';d.style.left=x+'px';d.style.top=y+'px';document.body.appendChild(d);setTimeout(()=>d.remove(),600)},[b.x+b.width/2,b.y+b.height/2]);
    await sleep(180);await el.click();};
  const shot=async n=>{await page.screenshot({path:path.join(__dirname,`shot_${n}.png`)})};
  mark('landing');await sleep(1800);
  mark('tapScan');await tap('#addPhotoBtn');
  await page.setInputFiles('#fridgePhotoInput',path.join(__dirname,'fridge_0064.jpg'));
  mark('photoAdded');await sleep(1800);await shot('photo');
  mark('tapGet');await tap('#analyseBtn');
  await sleep(2000);await shot('scan1');
  await sleep(2400);await shot('scan2');
  await sleep(1600);await shot('scan3');
  mark('afterChips');
  await page.waitForFunction(()=>document.getElementById('choiceCard').innerText.includes('Instamart'),null,{timeout:30000});
  mark('choiceReady');await sleep(1600);
  const scrollTo=async(sel,off,ms=900)=>{await page.evaluate(([sel,off,ms])=>new Promise(r=>{const el=document.querySelector(sel);const y0=scrollY;const y1=Math.max(0,el.getBoundingClientRect().top+scrollY-off);const t0=performance.now();const f=t=>{const p=Math.min(1,(t-t0)/ms);const e=p<.5?4*p*p*p:1-Math.pow(-2*p+2,3)/2;scrollTo(0,y0+(y1-y0)*e);p<1?requestAnimationFrame(f):r()};requestAnimationFrame(f)}),[sel,off,ms])};
  mark('cl0');await scrollTo('#recipeStatsRow',190);await sleep(2000);await shot('cl0');
  mark('cl1');await page.evaluate(()=>new Promise(r=>{const el=document.getElementById('recipeRowsContainer');const y0=el.scrollTop,y1=el.scrollHeight;const t0=performance.now(),ms=1300;const f=t=>{const p=Math.min(1,(t-t0)/ms);const e=p<.5?4*p*p*p:1-Math.pow(-2*p+2,3)/2;el.scrollTop=y0+(y1-y0)*e;p<1?requestAnimationFrame(f):r()};requestAnimationFrame(f)}));await sleep(2000);await shot('cl1');
  mark('choice');await scrollTo('#choiceCard',150,900);await sleep(1600);await shot('choice');
  mark('tapOrder');await tap('.choice-btn-primary');
  await sleep(1800);await shot('sheet');mark('sheet');
  await tap('#orderSheetConfirm');
  await sleep(1400);await shot('ordering');mark('ordering');
  await page.waitForFunction(()=>document.getElementById('orderCard').innerText.includes('Order confirmed'),null,{timeout:30000});
  await sleep(700);await scrollTo('#orderCard',170,900);
  mark('confirmed');await sleep(2200);await shot('confirmed');
  await sleep(1000);
  await cdp.send('Page.stopScreencast');
  fs.writeFileSync(path.join(__dirname,'cap.json'),JSON.stringify({frames,marks,T0}));
  console.log(n,'frames');await browser.close();
})();
